project_id = "dmpoandoydaqxhzdjnmk"

[functions.psa-scrape]
verify_jwt = false

[functions.shopify-webhook]
verify_jwt = false

[functions.shopify-import]
verify_jwt = false

[functions.shopify-config-check]
verify_jwt = false

[functions.shopify-webhook-test]
verify_jwt = false


